const problems = [
  // ─────────────────────────────────────────────
  // EASY
  // ─────────────────────────────────────────────
  {
    title: "URL Shortener",
    slug: "url-shortener",
    description:
      "Design a URL shortening service like bit.ly or TinyURL. The system should accept a long URL and return a unique short alias. When the short URL is visited, users are redirected to the original long URL. The service must handle millions of URL creation and redirection requests per day with low latency.",
    requirements: [
      "Generate a unique short code (6–8 characters) for any given long URL",
      "Redirect users from the short URL to the original URL with minimal latency",
      "Support custom aliases chosen by the user (e.g., /my-brand)",
      "Set optional expiry times on shortened URLs",
      "Track click analytics per short URL (count, timestamp, geo)",
      "Handle duplicate long URLs — optionally return the existing short code",
      "Provide a REST API for URL creation, retrieval, and deletion",
    ],
    constraints: [
      "100M new URLs created per day",
      "10:1 read-to-write ratio (1B redirects per day)",
      "Short codes must be unique across the system",
      "P99 redirect latency < 10 ms",
      "URLs and metadata stored for at least 5 years",
      "Short code length: 6–8 alphanumeric characters",
      "System must be highly available (99.99% uptime)",
    ],
    tags: ["hashing", "caching", "key-value store", "database", "REST API", "NoSQL"],
    difficulty: "easy",
    referenceComponents: [
      "Base62 encoding for short code generation",
      "Redis cache for hot URL lookups",
      "Consistent hashing for distributed storage",
      "SQL or NoSQL database for URL mappings",
      "Load balancer for API servers",
      "CDN for global redirect performance",
    ],
  },
  {
    title: "Pastebin",
    slug: "pastebin",
    description:
      "Design a text storage and sharing service similar to Pastebin.com. Users can paste arbitrary text or code snippets and receive a unique URL to share with others. Pastes can be public or private, and can optionally expire after a set duration. The service should handle read-heavy workloads efficiently.",
    requirements: [
      "Allow users to create pastes with arbitrary text or code content",
      "Generate a unique URL for each paste for sharing",
      "Support optional expiry (burn after read, 10 min, 1 hour, 1 day, 1 month, never)",
      "Support public and private (unlisted) pastes",
      "Allow registered users to view, edit, and delete their own pastes",
      "Support syntax highlighting for popular programming languages",
      "Provide paste analytics (view count) for the paste owner",
    ],
    constraints: [
      "Write: 1M new pastes per day; Read: 10M paste views per day",
      "Maximum paste size: 10 MB",
      "Store pastes for up to 10 years if no expiry is set",
      "99.9% availability required",
      "P95 read latency < 50 ms",
      "Unique key collision rate must be negligibly small",
    ],
    tags: ["object storage", "caching", "key-value store", "NoSQL", "CDN", "TTL"],
    difficulty: "easy",
    referenceComponents: [
      "Random key generation (Base58/Base62)",
      "Object storage (S3-compatible) for paste content",
      "Metadata database (PostgreSQL) for ownership, expiry, stats",
      "Redis for caching popular pastes and rate limiting",
      "TTL-based expiry worker / cron job",
      "CDN for serving static paste content",
    ],
  },
  {
    title: "Rate Limiter",
    slug: "rate-limiter",
    description:
      "Design a distributed rate limiting service that can be used as a standalone microservice or an API gateway middleware. It should restrict the number of requests a client (by IP, user ID, or API key) can make in a given time window, protecting backend services from abuse, DDoS attacks, and runaway clients.",
    requirements: [
      "Enforce configurable rate limits per client identifier (IP, user ID, API key)",
      "Support multiple rate limiting algorithms: token bucket, sliding window log, fixed window counter, and leaky bucket",
      "Allow different limits for different API endpoints or tiers",
      "Return clear HTTP 429 responses with Retry-After headers when limits are exceeded",
      "Distribute state across nodes so limits are enforced globally, not per-replica",
      "Support soft limits (warn) and hard limits (block)",
      "Expose an admin API for updating rules without redeployment",
    ],
    constraints: [
      "Must handle 100K requests per second globally",
      "Decision latency must be < 5 ms added overhead per request",
      "Rules must propagate across the cluster within 1 second",
      "At-least-once enforcement — occasional under-counting is acceptable, over-counting is not",
      "Support up to 10M unique client identifiers in the sliding window",
      "99.99% availability — a rate limiter outage should fail open, not block all traffic",
    ],
    tags: ["rate limiting", "token bucket", "sliding window", "Redis", "distributed systems", "API gateway"],
    difficulty: "easy",
    referenceComponents: [
      "Redis with atomic Lua scripts for counter operations",
      "Token bucket / sliding window counter implementation",
      "Centralized rule store (Redis or config service)",
      "API gateway integration layer",
      "Local in-memory cache per node to reduce Redis round trips",
      "Monitoring and alerting on limit breach rates",
    ],
  },
  {
    title: "Notification Service",
    slug: "notification-service",
    description:
      "Design a multi-channel notification service that enables applications to send push notifications, emails, and SMS messages to users at scale. The system should support templated messages, per-user channel preferences, delivery retries, and delivery receipts. It must handle millions of notifications per day reliably.",
    requirements: [
      "Support multiple channels: push notifications (iOS/Android), email, and SMS",
      "Allow senders to specify a template ID and personalization variables",
      "Respect per-user channel preferences and opt-out/unsubscribe settings",
      "Provide reliable delivery with automatic retries and exponential back-off",
      "Support both immediate (real-time) and scheduled notifications",
      "Track delivery status (sent, delivered, failed, bounced) per notification",
      "Provide a dashboard for delivery analytics and failure diagnostics",
    ],
    constraints: [
      "Handle 10M notifications per day at peak",
      "P99 delivery initiation latency < 1 second for real-time notifications",
      "Retry failed deliveries up to 5 times with exponential back-off",
      "Deduplicate notifications — same message to same user within 30s should not be sent twice",
      "Comply with opt-out and unsubscribe regulations (CAN-SPAM, GDPR)",
      "99.9% system availability",
    ],
    tags: ["message queue", "pub/sub", "push notifications", "email", "SMS", "async processing"],
    difficulty: "easy",
    referenceComponents: [
      "Message queue (Kafka / RabbitMQ) for notification events",
      "Worker pool per channel (email worker, SMS worker, push worker)",
      "Template engine for message personalization",
      "User preference store (database + Redis cache)",
      "Third-party integrations (Twilio, SendGrid, APNs, FCM)",
      "Dead letter queue for failed notification diagnostics",
    ],
  },
  {
    title: "Leaderboard",
    slug: "leaderboard",
    description:
      "Design a real-time leaderboard service for a gaming or competitive platform. The service must maintain globally ranked lists of users based on score, efficiently support top-K queries, and return a specific user's rank instantly. Score updates from millions of users should be reflected in near real-time.",
    requirements: [
      "Update a user's score and recompute their rank in real time",
      "Retrieve the global top-K players (e.g., top 100) with rank and score",
      "Query a specific user's current rank and nearby players (surrounding context)",
      "Support multiple leaderboards (per game, per season, per region)",
      "Reset leaderboards on a schedule (daily, weekly, seasonal)",
      "Handle concurrent score updates without race conditions",
      "Paginate through the full leaderboard",
    ],
    constraints: [
      "100M registered users, up to 10M concurrent during peak",
      "Score update rate: 5K updates per second",
      "Top-100 query latency: < 10 ms",
      "User rank query latency: < 10 ms",
      "Leaderboard must reflect updates within 1 second",
      "Support up to 1000 simultaneous leaderboards",
    ],
    tags: ["Redis sorted sets", "caching", "ranking", "real-time", "database", "pagination"],
    difficulty: "easy",
    referenceComponents: [
      "Redis Sorted Sets (ZADD, ZRANK, ZRANGE) for O(log N) rank operations",
      "Persistent store (PostgreSQL) for long-term score history",
      "Sharding strategy for multiple leaderboards",
      "Periodic snapshot to DB for durability",
      "Scheduled job for leaderboard resets",
      "API layer with pagination and filtering support",
    ],
  },
  {
    title: "Analytics Counter",
    slug: "analytics-counter",
    description:
      "Design a high-throughput analytics counting service that can track arbitrary events (page views, clicks, downloads, likes) at massive scale. The system should support real-time counter reads as well as aggregated time-series queries (hourly, daily, monthly totals). Think of it as the backbone for dashboards like YouTube view counts or Twitter like counts.",
    requirements: [
      "Increment counters for arbitrary event types and entity IDs",
      "Read the current count for any (entity, event) pair in real time",
      "Query aggregated counts over time windows (last 1h, 24h, 7d, 30d)",
      "Support high-cardinality entities (e.g., per-video, per-post, per-user)",
      "Handle sudden traffic spikes (viral events) without data loss",
      "Deduplication to avoid counting the same user action twice in a session",
      "Export aggregated data for downstream data warehousing",
    ],
    constraints: [
      "Ingest rate: 500K events per second at peak",
      "Counter reads: < 20 ms P99 latency",
      "Counts can lag real time by up to 5 seconds (eventual consistency acceptable)",
      "Data retention: raw events for 7 days, aggregates forever",
      "Up to 1B unique (entity, event) pairs",
      "99.9% system availability",
    ],
    tags: ["stream processing", "counting", "Redis", "Kafka", "time-series", "aggregation", "batch processing"],
    difficulty: "easy",
    referenceComponents: [
      "Event ingestion via Kafka for buffering spikes",
      "Redis counters (INCR) for real-time counts",
      "Stream processor (Flink / Spark Streaming) for aggregation",
      "Time-series database (ClickHouse / InfluxDB) for historical queries",
      "Bloom filter or session token for deduplication",
      "Batch export job to data warehouse (BigQuery / Redshift)",
    ],
  },
  {
    title: "File Upload Service",
    slug: "file-upload-service",
    description:
      "Design a service that allows users to securely upload, store, and download files of arbitrary type and size. The service should support resumable uploads for large files, enforce file size and type policies, and serve downloads efficiently. It should act as the upload backbone for consumer or enterprise applications.",
    requirements: [
      "Support single-part uploads for files up to 100 MB",
      "Support resumable multipart uploads for files up to 5 GB",
      "Generate a unique, secure file URL upon successful upload",
      "Enforce configurable file type allowlists and size limits",
      "Virus/malware scan uploaded files before making them accessible",
      "Support access control: public, private (presigned URL), or ACL-based",
      "Track upload metadata (uploader, size, type, timestamp, checksum)",
    ],
    constraints: [
      "Handle 50K concurrent uploads",
      "Maximum file size: 5 GB per file",
      "Upload throughput: 10 GB/s aggregate",
      "Files must be durable (99.999999999% — 11 nines) once committed",
      "Download latency: < 200 ms to first byte for files under 1 MB",
      "99.9% service availability",
    ],
    tags: ["object storage", "multipart upload", "presigned URL", "CDN", "streaming", "security"],
    difficulty: "easy",
    referenceComponents: [
      "Object storage backend (S3 / GCS / MinIO) for file persistence",
      "Presigned URL generation for secure direct-to-storage uploads",
      "Multipart upload coordinator for large file chunking",
      "Metadata database (PostgreSQL) for file records",
      "Async antivirus scanning worker (ClamAV / cloud AV API)",
      "CDN for fast global downloads",
    ],
  },
  {
    title: "Image Hosting Service",
    slug: "image-hosting-service",
    description:
      "Design an image hosting and serving platform similar to Imgur or Cloudinary. Users upload images which are stored durably and served globally at low latency. The service should support on-the-fly image transformations (resize, crop, format conversion, compression) via URL parameters, and serve optimized images for web and mobile clients.",
    requirements: [
      "Accept image uploads (JPEG, PNG, GIF, WebP, SVG) up to 20 MB",
      "Store originals durably and generate a shareable URL",
      "Serve on-the-fly transformations via URL parameters (?w=300&h=200&fmt=webp)",
      "Cache transformed variants to avoid reprocessing on every request",
      "Support public galleries and private images accessible via token",
      "Auto-generate thumbnails (small, medium, large) on upload",
      "Detect and reject NSFW or malicious images during upload",
    ],
    constraints: [
      "Upload rate: 10K images per minute at peak",
      "Serve 1B image requests per day",
      "Image transformation P99 latency: < 100 ms (cache miss), < 10 ms (cache hit)",
      "Storage durability: 99.999999999%",
      "Support images served from 20+ global edge locations",
      "99.99% availability for image serving",
    ],
    tags: ["object storage", "image processing", "CDN", "caching", "on-the-fly transformation", "media"],
    difficulty: "easy",
    referenceComponents: [
      "Object storage (S3 / GCS) for original image persistence",
      "Image processing service (Sharp / ImageMagick / libvips) for transformations",
      "CDN with edge caching for transformed variants",
      "Redis cache for transformation metadata",
      "Upload API with async thumbnail generation worker",
      "NSFW detection model (via ML API) on upload pipeline",
    ],
  },

  // ─────────────────────────────────────────────
  // MEDIUM
  // ─────────────────────────────────────────────
  {
    title: "Twitter Feed",
    slug: "twitter-feed",
    description:
      "Design the core news feed system for a microblogging platform like Twitter/X. Users post short text updates (tweets) and follow other users. The home timeline shows a reverse-chronological or ranked feed of tweets from accounts the user follows. The system must support millions of concurrent users and handle celebrity accounts with tens of millions of followers (the 'celebrity problem').",
    requirements: [
      "Users can post tweets (text up to 280 chars, optional media)",
      "Users can follow and unfollow other accounts",
      "Home timeline shows a feed of tweets from followed accounts, newest first",
      "Support likes, retweets, replies, and quote tweets",
      "Display trending topics / hashtags",
      "Support search over tweets (full-text and hashtag)",
      "Real-time delivery of new tweets to followers' timelines",
      "Notifications for mentions, likes, and new followers",
    ],
    constraints: [
      "300M daily active users",
      "500M tweets posted per day (~5800 TPS)",
      "Celebrities may have up to 100M followers",
      "Home timeline generation P99 < 500 ms",
      "Tweets must appear in followers' feeds within 5 seconds",
      "Store tweets and media for the lifetime of the account",
      "99.99% availability for timeline reads",
    ],
    tags: ["fan-out", "news feed", "pub/sub", "caching", "graph database", "CDN", "real-time", "search"],
    difficulty: "medium",
    referenceComponents: [
      "Fan-out on write (push model) for regular users",
      "Fan-out on read (pull model) for celebrities — hybrid approach",
      "Redis cache for pre-computed home timelines",
      "Graph store for follower/following relationships",
      "Kafka for async tweet delivery pipeline",
      "Elasticsearch for tweet search and trending topics",
      "CDN for media (images, videos)",
      "WebSocket / SSE for real-time timeline updates",
    ],
  },
  {
    title: "Instagram Feed",
    slug: "instagram-feed",
    description:
      "Design the core photo and video feed system for an Instagram-like social media platform. Users upload photos and short videos, follow other users, and see a ranked (algorithmically ordered) feed of content from their network. The system must handle massive media storage, on-the-fly media transcoding, and a sophisticated ranking pipeline.",
    requirements: [
      "Users can upload photos (up to 8 MB) and short videos (up to 60 seconds)",
      "Users can follow/unfollow other accounts and browse a personalized feed",
      "Feed is ranked by an ML model (engagement signals, recency, relationship strength)",
      "Support Stories (ephemeral 24-hour posts) separate from the main feed",
      "Support likes, comments, saves, and shares on posts",
      "Discover / Explore page with content from outside the follow graph",
      "Real-time activity notifications",
      "Media transcoding: multiple resolutions for adaptive streaming",
    ],
    constraints: [
      "500M DAU, 1B MAU",
      "100M photos and videos uploaded per day",
      "Feed generation P99 < 1 second",
      "Media storage: tens of petabytes",
      "Stories expire automatically after 24 hours",
      "Video must support adaptive bitrate streaming",
      "99.99% availability for feed reads",
    ],
    tags: ["media transcoding", "fan-out", "ML ranking", "CDN", "object storage", "real-time", "recommendations"],
    difficulty: "medium",
    referenceComponents: [
      "Object storage (S3) for raw and transcoded media",
      "Transcoding pipeline (FFmpeg workers) for video formats and resolutions",
      "Ranking service with feature store and ML model serving",
      "Fan-out service (hybrid push/pull) for feed assembly",
      "Redis cache for feed segments and story views",
      "CDN with adaptive bitrate streaming support",
      "Kafka for async event processing (likes, views, uploads)",
    ],
  },
  {
    title: "WhatsApp",
    slug: "whatsapp",
    description:
      "Design a large-scale instant messaging application similar to WhatsApp. Users can send text, voice, images, and documents in one-on-one and group chats. Messages are delivered in real time with end-to-end encryption, and delivery receipts (sent, delivered, read) are shown per message. The system must maintain persistent connections for billions of devices.",
    requirements: [
      "One-on-one and group messaging (up to 1024 members per group)",
      "Support message types: text, image, video, audio, document, location",
      "End-to-end encryption using the Signal Protocol",
      "Message delivery receipts: sent (✓), delivered (✓✓), read (✓✓ blue)",
      "Offline message queuing — deliver messages when the recipient comes online",
      "Voice and video calls (WebRTC-based)",
      "Last seen and online presence indicators",
      "Push notifications when the app is backgrounded",
    ],
    constraints: [
      "2B registered users, 500M DAU",
      "100B messages sent per day",
      "Maintain persistent WebSocket connections for 500M concurrent users",
      "Message delivery latency < 100 ms when recipient is online",
      "Offline messages retained for up to 30 days",
      "Media files up to 100 MB per message",
      "99.99% availability for message delivery",
    ],
    tags: ["WebSocket", "real-time messaging", "end-to-end encryption", "pub/sub", "message queue", "presence", "WebRTC"],
    difficulty: "medium",
    referenceComponents: [
      "Persistent WebSocket connection server (chat server)",
      "Message router and delivery service",
      "Offline message queue (Kafka / custom queue) per user",
      "Signal Protocol for E2E encryption key management",
      "Presence service with Redis for online/last-seen status",
      "Media storage (object storage + CDN) with encryption",
      "Push notification gateway (APNs / FCM) for backgrounded apps",
      "WebRTC signaling server for voice/video calls",
    ],
  },
  {
    title: "Slack",
    slug: "slack",
    description:
      "Design a team collaboration and messaging platform similar to Slack. The system supports workspaces, channels (public and private), direct messages, threads, and file sharing. Real-time message delivery, search over message history, and integrations with external services (bots, webhooks) are core requirements.",
    requirements: [
      "Workspaces with members, roles (admin, member, guest)",
      "Public, private, and DM channels; DM threads",
      "Real-time message delivery to all channel members",
      "Threaded replies on any message",
      "Reactions (emoji) on messages",
      "Full-text search across all messages in a workspace",
      "File uploads and previews (images, PDFs, code snippets)",
      "Webhook ingestion and bot framework for integrations",
      "Presence (online / away / DND) and typing indicators",
      "Push notifications and email digests for offline users",
    ],
    constraints: [
      "10M workspaces, 20M DAU",
      "Message delivery latency < 200 ms within a channel",
      "Full-text search index must stay within 2 minutes of real time",
      "Message history retained forever (or per workspace plan)",
      "Support channels with up to 10K members",
      "99.9% availability for messaging",
    ],
    tags: ["WebSocket", "real-time", "full-text search", "pub/sub", "message queue", "Elasticsearch", "channels", "collaboration"],
    difficulty: "medium",
    referenceComponents: [
      "WebSocket server per region for persistent client connections",
      "Channel fan-out service with pub/sub (Kafka topics per channel)",
      "Message persistence store (Cassandra / DynamoDB) keyed by (channel, timestamp)",
      "Elasticsearch index for full-text search",
      "Presence service (Redis TTL-based) for online/away state",
      "File storage (S3) with inline preview generator",
      "Webhook ingestion service with rate limiting",
    ],
  },
  {
    title: "Dropbox",
    slug: "dropbox",
    description:
      "Design a file synchronization and cloud storage service similar to Dropbox. Users install a client on their devices; any file change is automatically synced to the cloud and pushed to all other linked devices. The system must support efficient delta sync (only changed bytes are transferred), conflict resolution, and sharing files or folders with other users.",
    requirements: [
      "Sync files across multiple devices for a user (desktop, mobile, web)",
      "Detect and upload only changed chunks of a file (delta/chunked sync)",
      "Propagate file changes to other linked devices in near real time",
      "Conflict resolution when the same file is edited on two devices offline",
      "File versioning — restore any previous version of a file",
      "Share files and folders with other users (view/edit permissions)",
      "Selective sync — choose which folders to sync on each device",
    ],
    constraints: [
      "500M registered users, 100M DAU",
      "Store total of 1 exabyte across all users",
      "Maximum file size: 50 GB",
      "File change must appear on other devices within 5 seconds (when online)",
      "Support clients on Windows, macOS, Linux, iOS, Android, and web",
      "99.999% storage durability",
      "99.9% sync service availability",
    ],
    tags: ["file sync", "chunking", "delta sync", "object storage", "conflict resolution", "versioning", "WebSocket"],
    difficulty: "medium",
    referenceComponents: [
      "Client-side chunking (4 MB blocks) with content-defined chunking",
      "Block deduplication service (hash-based) for storage efficiency",
      "Metadata database (file tree, versions, ownership) — sharded PostgreSQL",
      "Object storage (S3) for block storage",
      "Sync notification service (long polling or WebSocket) for device wake-up",
      "Conflict detection via vector clocks or last-writer-wins with copy",
      "CDN for web access to files",
    ],
  },
  {
    title: "Google Drive",
    slug: "google-drive",
    description:
      "Design a cloud storage and collaborative document platform similar to Google Drive. Beyond file storage, the system supports real-time collaborative editing of documents, spreadsheets, and presentations natively in the browser. Multiple users can edit the same document simultaneously and see each other's cursors and changes in real time.",
    requirements: [
      "Store, organize, and share files and folders in a hierarchical structure",
      "Real-time collaborative editing with operational transformation or CRDTs",
      "Support multi-user simultaneous editing with cursor presence",
      "Role-based sharing: viewer, commenter, editor, owner",
      "Full-text search over file names and document contents",
      "File versioning with named snapshots and restore",
      "Offline editing with automatic sync when back online",
      "Native apps for mobile that mirror the web experience",
    ],
    constraints: [
      "2B users, 1B files uploaded per day",
      "Real-time collaboration: changes visible to all editors < 200 ms",
      "Support up to 100 simultaneous editors on a single document",
      "Store 15 GB free per user; support up to 30 TB paid storage",
      "Full-text search results within 500 ms",
      "99.99% availability for document access",
    ],
    tags: ["operational transformation", "CRDT", "real-time collaboration", "object storage", "full-text search", "conflict resolution", "WebSocket"],
    difficulty: "medium",
    referenceComponents: [
      "Operational Transformation (OT) or CRDT engine for collaborative edits",
      "Real-time sync server (WebSocket) per document session",
      "Document state store (Redis for live state, persistent DB for snapshots)",
      "Object storage (GCS / S3) for non-native files",
      "Search index (Elasticsearch) over document contents",
      "Presence service for cursor positions and active editors",
      "Offline sync queue on the client with merge-on-reconnect",
    ],
  },
  {
    title: "Calendar",
    slug: "calendar",
    description:
      "Design a distributed calendar and scheduling service similar to Google Calendar. Users can create, edit, and delete events, invite other users, and receive reminders. The system must handle recurring events efficiently, resolve scheduling conflicts, support time zones, and sync in real time across multiple devices.",
    requirements: [
      "Create, update, delete calendar events with title, description, time, location",
      "Invite attendees and track their RSVP status (accepted, declined, tentative)",
      "Support recurring events (daily, weekly, monthly, custom RRULE patterns)",
      "Send email and push notification reminders before events",
      "Sync events across all devices in real time",
      "Support multiple calendars per user (work, personal, shared)",
      "Free/busy queries for scheduling across multiple users",
      "Full CalDAV/iCalendar protocol support for third-party clients",
    ],
    constraints: [
      "500M users, 5B events stored",
      "Recurring events can have up to 10 years of occurrences",
      "Event updates must sync to all devices within 5 seconds",
      "Reminders delivered within 1 minute of scheduled time",
      "Support 100K concurrent event creation/update requests",
      "Handle time zone conversions accurately across all 400+ IANA time zones",
      "99.9% availability",
    ],
    tags: ["recurring events", "time zones", "notifications", "CalDAV", "real-time sync", "scheduling", "conflict resolution"],
    difficulty: "medium",
    referenceComponents: [
      "RRULE (RFC 5545) expansion engine for recurring events",
      "Event store (PostgreSQL) with efficient range queries by user and time",
      "Reminder scheduler service (cron-based with priority queue)",
      "Real-time sync via WebSocket or push (Firebase / APNs / FCM)",
      "Time zone database (IANA tzdata) integration layer",
      "CalDAV server for third-party calendar client compatibility",
      "Free/busy index for cross-user availability queries",
    ],
  },
  {
    title: "News Feed",
    slug: "news-feed",
    description:
      "Design a personalized news feed system similar to Facebook's News Feed. The feed aggregates content from a user's social graph (friends, pages, groups) and ranks it using an ML model based on relevance, engagement, recency, and diversity. The system must serve a highly personalized ranked feed to billions of users with low latency.",
    requirements: [
      "Aggregate posts from a user's friends, pages, and groups",
      "Rank feed items using ML signals: engagement, recency, post type, relationship strength",
      "Support diverse content types: text posts, photos, videos, links, events, stories",
      "Insert sponsored posts at configurable positions without degrading UX",
      "Real-time update when a close friend posts (within 5 seconds)",
      "Infinite scroll with paginated feed loading",
      "User controls: hide post, unfollow source, snooze for 30 days, report",
      "Support for 'Memories' — surfacing content from past years",
    ],
    constraints: [
      "2B DAU",
      "Each user follows on average 300 friends/pages/groups",
      "Feed generation P99 < 1 second",
      "Feed must feel 'fresh' — show new content within 5 minutes of posting for top friends",
      "Ranking model must re-score candidate pool within 200 ms",
      "Store post data and engagement signals forever",
      "99.99% availability",
    ],
    tags: ["ML ranking", "fan-out", "candidate generation", "feature store", "caching", "social graph", "real-time"],
    difficulty: "medium",
    referenceComponents: [
      "Candidate retrieval service (pull from interest graph + social graph)",
      "Feature store for real-time and batch engagement signals",
      "ML ranking service (low-latency model serving)",
      "Pre-computed feed cache per user (Redis) refreshed on new posts",
      "Fan-out service: push for close friends, pull for pages/groups",
      "Ad insertion service with frequency capping",
      "Social graph store (TAO-style, graph DB)",
    ],
  },
  {
    title: "Collaborative Document Editor",
    slug: "collaborative-document-editor",
    description:
      "Design a real-time collaborative document editing service similar to Google Docs or Notion. Multiple users can simultaneously edit the same document and see each other's changes instantly without conflicts. The system must handle concurrent edits, maintain document consistency, support rich text formatting, and provide a complete version history.",
    requirements: [
      "Multiple users can edit the same document simultaneously in real time",
      "Changes from all editors are merged without conflicts (OT or CRDT)",
      "Show live cursors and selections of all active collaborators",
      "Support rich text: headings, bold, italic, lists, tables, images, code blocks",
      "Comment threads anchored to specific text ranges",
      "Complete version history with named versions and full restore capability",
      "Offline editing with automatic conflict-free merge on reconnect",
      "Role-based permissions: view, comment, edit, owner",
    ],
    constraints: [
      "Support up to 200 concurrent editors on a single document",
      "Change propagation to all editors < 100 ms within a region",
      "Documents can be up to 500 MB in raw storage",
      "Version history stored indefinitely",
      "Consistency guarantee: all editors converge to the same document state",
      "99.99% availability for document access",
    ],
    tags: ["CRDT", "operational transformation", "real-time collaboration", "WebSocket", "conflict resolution", "version history", "presence"],
    difficulty: "medium",
    referenceComponents: [
      "CRDT (e.g., Yjs, Automerge) or OT engine for conflict-free merging",
      "WebSocket server for real-time bidirectional edit streaming",
      "Document state store (Redis for active sessions, S3 for snapshots)",
      "Presence service for cursor/selection awareness",
      "Version history store (append-only operation log)",
      "Permission service with ACL enforcement",
      "Offline client sync queue with merge-on-reconnect logic",
    ],
  },

  // ─────────────────────────────────────────────
  // HARD
  // ─────────────────────────────────────────────
  {
    title: "YouTube",
    slug: "youtube",
    description:
      "Design a large-scale video sharing and streaming platform similar to YouTube. Users upload videos that are transcoded into multiple resolutions for adaptive bitrate streaming. A recommendation engine surfaces relevant videos on the home page and 'Up Next' sidebar. The system must handle massive video storage, global CDN delivery, and billions of daily views.",
    requirements: [
      "Video upload pipeline supporting files up to 128 GB",
      "Transcoding to multiple resolutions (360p, 480p, 720p, 1080p, 4K) and formats (HLS/DASH)",
      "Adaptive bitrate streaming to clients based on bandwidth",
      "Personalized video recommendations on home feed and Up Next",
      "Search over video titles, descriptions, captions, and transcripts",
      "Likes, dislikes, comments, shares, and view count per video",
      "Channel subscriptions with notification on new upload",
      "Live streaming with < 10 second end-to-end latency",
      "Creator Studio analytics (views, watch time, revenue)",
    ],
    constraints: [
      "500 hours of video uploaded every minute",
      "2B logged-in users, 1B hours watched per day",
      "Video must be available for streaming within 5 minutes of upload",
      "Video serve latency: < 2 seconds to first frame globally",
      "Transcode farm must process 500 hrs/min of source video",
      "Storage: multi-exabyte object store",
      "CDN must serve 1B+ streams per day globally",
      "99.99% availability for video playback",
    ],
    tags: ["video transcoding", "adaptive streaming", "CDN", "recommendations", "search", "object storage", "live streaming", "HLS/DASH"],
    difficulty: "hard",
    referenceComponents: [
      "Upload service with resumable multipart uploads",
      "Transcoding pipeline (distributed FFmpeg workers, GPU-accelerated)",
      "HLS/DASH packaging service for adaptive streaming",
      "Object storage (GCS/S3) for raw and transcoded video segments",
      "Global CDN with edge PoPs for video delivery",
      "Recommendation engine (two-tower neural model, candidate retrieval + ranking)",
      "Video search with Elasticsearch over metadata and transcript index",
      "Live streaming ingest (RTMP) → segmenter → CDN push",
      "View count and watch-time analytics pipeline (Kafka + ClickHouse)",
    ],
  },
  {
    title: "Netflix",
    slug: "netflix",
    description:
      "Design a global video streaming service similar to Netflix. The system must store a large catalog of movies and shows, encode them at multiple quality levels, and stream them to hundreds of millions of users across diverse devices and network conditions. A personalized recommendation system drives content discovery. The service must achieve near-100% availability for playback.",
    requirements: [
      "Catalog management: ingest, encode, and publish movies and TV shows",
      "Adaptive bitrate streaming to TVs, browsers, phones, and game consoles",
      "Personalized homepage with recommendations and 'Continue Watching'",
      "Multiple profiles per account with separate recommendation history",
      "Support for offline downloads on mobile apps",
      "Subtitle and multi-audio track support",
      "DRM (Widevine, FairPlay, PlayReady) for content protection",
      "Billing and subscription tier management (SD, HD, UHD)",
      "CDN edge caching to pre-position popular content",
    ],
    constraints: [
      "230M paid subscribers in 190 countries",
      "Streaming service must be available 24/7 with < 0.01% error rate",
      "Serve 200M+ streaming hours per day",
      "Support 2K simultaneous bitrate profiles per title",
      "Content must be DRM-protected end-to-end",
      "Playback must start within 2 seconds globally",
      "Encode and publish new content within 24 hours of ingest",
      "Support 100+ device types and player implementations",
    ],
    tags: ["video streaming", "adaptive bitrate", "CDN", "DRM", "transcoding", "recommendations", "offline downloads", "HLS/DASH"],
    difficulty: "hard",
    referenceComponents: [
      "Encoding pipeline (per-title encoding, VMAF quality optimization)",
      "Open Connect CDN (ISP-embedded appliances) for content pre-positioning",
      "Adaptive streaming manifest service (HLS/DASH)",
      "DRM license server (Widevine / FairPlay integration)",
      "Recommendation engine (contextual bandits + deep learning)",
      "API gateway with Zuul-style routing for microservices",
      "Chaos engineering framework (Chaos Monkey) for resilience testing",
      "Billing and subscription service with dunning logic",
    ],
  },
  {
    title: "Uber",
    slug: "uber",
    description:
      "Design a ride-sharing platform similar to Uber. Riders request trips, the system matches them with nearby available drivers in real time, and both parties track each other on a live map during the trip. The system must handle geospatial queries at massive scale, compute surge pricing dynamically, and guarantee reliable matching even during peak demand.",
    requirements: [
      "Rider sends trip request with pickup and destination",
      "Match rider to the nearest suitable available driver within seconds",
      "Real-time GPS location updates from drivers (every 4 seconds)",
      "Live map showing driver's approach and en-route progress for rider",
      "Dynamic surge pricing based on supply/demand in geo cells",
      "Estimated time of arrival (ETA) calculation",
      "Trip lifecycle: request → accept → pickup → in-trip → completed → payment",
      "Ratings and reviews post-trip for both rider and driver",
      "Driver earnings dashboard and weekly payout",
    ],
    constraints: [
      "8M trips per day, 5M registered drivers worldwide",
      "Driver location updates: 1M GPS pings per second globally",
      "Matching latency < 1 second from request submission",
      "Matched driver must appear on rider's map within 2 seconds",
      "Surge pricing must recompute every 60 seconds per geo cell",
      "ETA accuracy: within ± 1 minute",
      "99.99% availability for trip booking",
    ],
    tags: ["geospatial", "real-time matching", "location tracking", "WebSocket", "surge pricing", "maps", "payment processing"],
    difficulty: "hard",
    referenceComponents: [
      "Location ingestion service (high-throughput GPS event pipeline via Kafka)",
      "Geospatial index (H3 hexagons or S2 cells) for nearby driver queries",
      "Matching service with scoring (distance, rating, vehicle type, ETA)",
      "Supply/demand aggregator for surge pricing per geo cell",
      "Trip state machine service with distributed locks",
      "WebSocket push for real-time location updates to rider and driver",
      "Routing / ETA service (integration with mapping engine or OSRM)",
      "Payment service with idempotency guarantees",
    ],
  },
  {
    title: "Food Delivery App",
    slug: "food-delivery-app",
    description:
      "Design a food delivery platform similar to DoorDash or Uber Eats. Customers browse restaurant menus, place orders, and track a delivery driver in real time. The platform must handle real-time order orchestration across three parties (customer, restaurant, driver), optimize driver-order dispatch, and handle peak demand (lunch/dinner rush) gracefully.",
    requirements: [
      "Restaurant discovery with filters (cuisine, rating, delivery time, price)",
      "Browse menu, customize items, and add to cart",
      "Checkout with payment, tip, and delivery address",
      "Restaurant receives and confirms order; prepares in estimated time",
      "Automated or manual driver dispatch to the restaurant",
      "Real-time order status tracking: confirmed → preparing → picked up → delivered",
      "Live map showing driver's location during delivery",
      "Ratings and reviews for restaurants and drivers post-delivery",
      "Promotions, coupons, and loyalty rewards",
    ],
    constraints: [
      "20M orders per day at peak",
      "Order confirmation to restaurant within 2 seconds",
      "Driver dispatch decision within 10 seconds of order confirmation",
      "Driver location updates every 5 seconds",
      "Payment success rate > 99.5%",
      "99.99% availability for order placement",
      "Support operations in 50+ countries with local payment methods",
    ],
    tags: ["real-time order management", "geospatial dispatch", "WebSocket", "payment", "location tracking", "notifications", "marketplace"],
    difficulty: "hard",
    referenceComponents: [
      "Order management state machine (customer, restaurant, driver states)",
      "Driver dispatch service with geospatial scoring and ETA estimates",
      "Location ingestion pipeline (Kafka) for driver GPS pings",
      "Geospatial index (H3 / PostGIS) for nearby driver queries",
      "Real-time notification service (WebSocket + push) for all parties",
      "Payment service with idempotency, retries, and fraud detection",
      "Restaurant portal with order acceptance and kitchen display integration",
      "Promotion engine with coupon validation and discount stacking rules",
    ],
  },
  {
    title: "Search Engine",
    slug: "search-engine",
    description:
      "Design a large-scale web search engine similar to Google Search. The system crawls billions of web pages, builds an inverted index, and returns the most relevant ranked results for any user query within milliseconds. It must handle spelling correction, query understanding, result ranking using hundreds of signals, and serve billions of queries per day.",
    requirements: [
      "Crawl and index billions of web pages continuously",
      "Build and maintain an inverted index for full-text search",
      "Query understanding: spelling correction, synonyms, entity recognition, intent classification",
      "Rank results using a multi-signal relevance model (TF-IDF, PageRank, ML)",
      "Return top results with title, snippet, and URL within 200 ms",
      "Support search operators (site:, filetype:, -exclude, \"exact phrase\")",
      "Personalized results based on user search history",
      "Knowledge panel for entities (people, places, companies)",
      "Real-time freshness for news and trending queries",
    ],
    constraints: [
      "Index 100B+ web pages; update incrementally as pages change",
      "100K search queries per second globally",
      "Query response latency < 200 ms at P99",
      "Crawl budget: 10B pages per day",
      "Index update freshness: important pages re-indexed within 24 hours",
      "Storage for index: multiple petabytes",
      "99.99% query serving availability",
    ],
    tags: ["inverted index", "web crawler", "PageRank", "TF-IDF", "ML ranking", "MapReduce", "Bigtable", "distributed systems"],
    difficulty: "hard",
    referenceComponents: [
      "Distributed web crawler (politeness, deduplication, priority queue)",
      "Inverted index builder (MapReduce / Spark over crawled corpus)",
      "Index serving tier (sharded, replicated Bigtable-style store)",
      "Query processor (query parsing, operator support, expansion)",
      "ML ranking model (LambdaMART / neural ranking) with feature store",
      "PageRank computation (iterative distributed graph algorithm)",
      "Spelling corrector (noisy channel model + N-gram language model)",
      "Knowledge graph for entity panels",
      "Real-time index for fresh content (separate index tier for news)",
    ],
  },
  {
    title: "Web Crawler",
    slug: "web-crawler",
    description:
      "Design a large-scale distributed web crawler that systematically downloads and stores web pages for indexing or analysis. The crawler must respect robots.txt, avoid re-crawling unchanged pages too frequently, detect and handle duplicate content, and crawl billions of pages per day without overwhelming any single domain.",
    requirements: [
      "Discover and crawl URLs starting from a seed set",
      "Respect robots.txt politeness policies and crawl delays",
      "Detect and skip duplicate URLs and near-duplicate content (Simhash)",
      "Prioritize crawl order by page importance (PageRank estimate) and freshness",
      "Extract and enqueue outgoing links from crawled pages",
      "Store raw HTML and metadata (URL, crawl time, HTTP headers, status) durably",
      "Support re-crawling pages on a schedule based on change frequency",
      "Handle various content types: HTML, PDF, images, sitemaps",
    ],
    constraints: [
      "Crawl rate: 10B pages per day (~115K pages/second)",
      "URL frontier can hold up to 1T URLs",
      "Politeness: no more than 1 request per second per domain",
      "Deduplication: URL-level (exact) and content-level (near-duplicate)",
      "Crawled content stored at petabyte scale",
      "DNS resolution must be cached to avoid bottlenecks",
      "Handle 5xx errors and timeouts gracefully with back-off and retry",
    ],
    tags: ["distributed crawling", "URL frontier", "robots.txt", "Bloom filter", "Simhash", "deduplication", "scheduling", "big data"],
    difficulty: "hard",
    referenceComponents: [
      "URL frontier (priority queue of URLs to crawl) backed by distributed queue",
      "Bloom filter for URL-level deduplication (already seen check)",
      "DNS cache layer to reduce DNS resolution overhead",
      "Fetcher worker pool with per-domain rate limiting",
      "HTML parser and link extractor",
      "Simhash-based near-duplicate detector for content-level dedup",
      "Object storage (S3) for raw HTML and metadata",
      "Scheduler service for recrawl based on page change frequency model",
    ],
  },
  {
    title: "Distributed Cache",
    slug: "distributed-cache",
    description:
      "Design a distributed in-memory caching system similar to Memcached or Redis Cluster. The system should partition data across nodes using consistent hashing, handle node additions and removals gracefully with minimal data redistribution, support eviction policies, and serve get/set requests at sub-millisecond latency under high throughput.",
    requirements: [
      "Support GET, SET, DELETE, and TTL-based expiry operations",
      "Distribute data across multiple nodes using consistent hashing",
      "Handle node failures and additions with minimal cache invalidation (< 1/N keys remapped)",
      "Multiple eviction policies: LRU, LFU, TTL, and random",
      "Replication for high availability: primary-replica pairs per shard",
      "Cache-aside, write-through, and write-behind caching patterns",
      "Client-side library to abstract consistent hashing and routing",
      "Monitoring: hit/miss rates, memory usage, eviction count, latency percentiles",
    ],
    constraints: [
      "Sub-millisecond P99 GET latency",
      "Support 1M operations per second per node",
      "Total cluster capacity: terabytes of cached data",
      "Node failure detection within 5 seconds; automatic failover",
      "Adding a new node should redistribute only 1/N of keys",
      "99.99% availability for read operations",
    ],
    tags: ["consistent hashing", "LRU eviction", "replication", "distributed systems", "in-memory", "cache", "fault tolerance"],
    difficulty: "hard",
    referenceComponents: [
      "Consistent hashing ring with virtual nodes for even distribution",
      "In-memory hash table with LRU eviction (doubly linked list + hash map)",
      "Primary-replica replication with async log shipping",
      "Gossip protocol for cluster membership and failure detection",
      "Client library with connection pooling and routing logic",
      "Persistence option: RDB snapshots or AOF write-ahead log",
      "Monitoring agent exposing metrics to Prometheus / StatsD",
    ],
  },
  {
    title: "Distributed Key-Value Store",
    slug: "distributed-key-value-store",
    description:
      "Design a distributed key-value store similar to Amazon DynamoDB or Apache Cassandra. Unlike a cache, the store offers durability guarantees. It must partition data across nodes, replicate for fault tolerance, handle concurrent writes with configurable consistency levels, and provide tunable availability vs. consistency trade-offs (CAP theorem).",
    requirements: [
      "Support GET, PUT, DELETE operations with arbitrary byte-string keys and values",
      "Partition data across nodes using consistent hashing",
      "Replicate each key to N nodes for fault tolerance (configurable N)",
      "Configurable consistency: eventual, quorum (R+W > N), or strong",
      "Conflict resolution for concurrent writes: vector clocks or last-write-wins",
      "Hinted handoff for writes when a target replica is temporarily unavailable",
      "Anti-entropy using Merkle trees for replica synchronization",
      "Range scans over lexicographically ordered keys",
    ],
    constraints: [
      "P99 GET latency < 10 ms at quorum consistency",
      "P99 PUT latency < 20 ms at quorum consistency",
      "Data durability: 99.999999999%",
      "Support nodes joining and leaving without downtime",
      "Handle network partitions gracefully (remain available for writes with eventual consistency)",
      "Scale to petabytes of data across hundreds of nodes",
    ],
    tags: ["consistent hashing", "replication", "vector clocks", "Merkle trees", "quorum", "CAP theorem", "eventual consistency", "LSM tree"],
    difficulty: "hard",
    referenceComponents: [
      "Consistent hashing ring with virtual nodes for data partitioning",
      "LSM-tree (Log-Structured Merge-tree) for write-optimized local storage",
      "Quorum-based read/write with configurable R and W values",
      "Vector clocks for causal conflict tracking",
      "Hinted handoff queue for writes to temporarily unavailable nodes",
      "Merkle tree anti-entropy service for background replica repair",
      "Gossip protocol for cluster membership, failure detection, and metadata propagation",
    ],
  },
  {
    title: "Distributed Messaging System",
    slug: "distributed-messaging-system",
    description:
      "Design a distributed messaging / event streaming system similar to Apache Kafka. Producers publish messages to topics, which are partitioned and replicated across a broker cluster. Consumers read messages from topics, with guaranteed ordering within a partition and at-least-once or exactly-once delivery semantics. The system must handle millions of messages per second durably.",
    requirements: [
      "Producers publish messages to named topics; consumers subscribe and read",
      "Partition topics for parallel consumption; preserve ordering within a partition",
      "Replicate partitions across N brokers for fault tolerance",
      "Persist messages to disk and retain them for a configurable duration (e.g., 7 days)",
      "Consumer groups: multiple consumers share a topic's partitions for parallel processing",
      "Support at-least-once and exactly-once delivery semantics",
      "Backpressure and flow control between producers and brokers",
      "Schema registry for message format validation (Avro/Protobuf/JSON Schema)",
    ],
    constraints: [
      "Write throughput: 1M messages per second per cluster",
      "P99 producer acknowledgement latency < 10 ms",
      "Messages must be durable once acknowledged (fsync to disk)",
      "Replay messages from any offset within retention window",
      "Consumer lag monitoring per consumer group",
      "Leader election for partition replicas within 10 seconds of broker failure",
      "Horizontal scale: add brokers without downtime",
    ],
    tags: ["Kafka", "partitioning", "replication", "event streaming", "message queue", "exactly-once", "leader election", "consumer groups"],
    difficulty: "hard",
    referenceComponents: [
      "Broker nodes with log-structured persistent message storage per partition",
      "ZooKeeper or KRaft for cluster metadata and leader election",
      "Producer with configurable acks (0, 1, all) and batching",
      "Consumer group coordinator for partition assignment (range / round-robin)",
      "Exactly-once via idempotent producer IDs and transactional API",
      "Replication protocol: leader handles all reads/writes, followers replicate",
      "Schema registry service with compatibility enforcement",
      "Monitoring: per-partition lag, throughput, and broker health",
    ],
  },
  {
    title: "Google Maps",
    slug: "google-maps",
    description:
      "Design a large-scale mapping and navigation service similar to Google Maps. The system must store and render detailed maps of the world, provide turn-by-turn routing between any two points, estimate travel times in real time using live traffic data, and support features like place search, reviews, and street-level imagery.",
    requirements: [
      "Render interactive maps with zoom levels 0–20 globally",
      "Search for places (businesses, addresses, landmarks) with autocomplete",
      "Compute shortest-path routes (driving, walking, transit, cycling) between two points",
      "Incorporate real-time traffic data into ETA and route re-calculation",
      "Turn-by-turn navigation with voice guidance and rerouting",
      "Display place details: hours, phone, website, ratings, reviews, photos",
      "Satellite and Street View imagery",
      "Support offline maps download for a region",
    ],
    constraints: [
      "Store map data for the entire Earth (TB–PB of vector and raster data)",
      "Map tile rendering latency < 50 ms at edge",
      "Route computation: < 500 ms for cross-continent routes",
      "Real-time traffic updates ingested from 1B+ GPS probes per day",
      "1B+ map requests per day",
      "Search autocomplete results < 100 ms",
      "99.99% availability for map and routing services",
    ],
    tags: ["geospatial", "graph algorithms", "Dijkstra", "A*", "map tiles", "CDN", "real-time traffic", "spatial indexing"],
    difficulty: "hard",
    referenceComponents: [
      "Road network graph (compressed adjacency list) stored in a spatial DB",
      "Shortest-path algorithms: Dijkstra / A* / Contraction Hierarchies for fast routing",
      "Map tile server: vector tiles generated from OSM-style data; served via CDN",
      "Traffic ingestion pipeline (GPS probes → speed aggregation per road segment)",
      "Place search: Elasticsearch with geospatial indexing",
      "ETA service: real-time traffic-adjusted shortest path",
      "Offline map packaging service (region extraction + tile bundling)",
      "Street View: panoramic image storage and projection service",
    ],
  },
  {
    title: "Ad Click Tracking System",
    slug: "ad-click-tracking-system",
    description:
      "Design a high-throughput ad click and impression tracking system similar to those used by Google or Meta Ads. The system must record billions of ad impressions and clicks per day, attribute conversions to the correct ads, and provide near-real-time and batch analytics dashboards for advertisers. Accuracy, deduplication, and fraud detection are critical.",
    requirements: [
      "Record ad impressions and clicks with low latency (fire-and-forget from client)",
      "Attribute clicks and conversions (purchases, sign-ups) to the correct ad campaign",
      "Deduplicate events — a single double-click should count as one click",
      "Detect and filter fraudulent clicks (bot traffic, click farms)",
      "Provide real-time reporting: spend, impressions, clicks, CTR per campaign",
      "Provide batch analytics: daily/weekly reports with demographic breakdowns",
      "Billing: charge advertisers accurately based on verified click counts",
      "Data retention: raw events for 90 days, aggregates for 7 years",
    ],
    constraints: [
      "Ingest 1M ad events per second (impressions + clicks)",
      "Event recording latency must not impact page load (< 50 ms from CDN)",
      "Deduplication window: 30 seconds per (ad ID, user ID)",
      "Real-time dashboard refresh: < 5 minutes lag",
      "Billing data must be exact — no over or under-charging",
      "Fraud detection decision within 1 second of event",
      "99.99% availability for event ingestion",
    ],
    tags: ["event tracking", "stream processing", "Kafka", "ClickHouse", "fraud detection", "aggregation", "attribution", "big data"],
    difficulty: "hard",
    referenceComponents: [
      "Pixel / beacon endpoint served from CDN edge for fast event capture",
      "Kafka ingest pipeline for high-throughput event buffering",
      "Deduplication service (Redis with sliding window bloom filter)",
      "Stream processor (Flink / Spark Streaming) for real-time aggregation",
      "Fraud detection ML service (bot scoring, click pattern anomaly detection)",
      "Batch ETL pipeline to data warehouse (BigQuery / Redshift / ClickHouse)",
      "Attribution service (last-click, first-click, multi-touch models)",
      "Billing reconciliation service with idempotent charge records",
    ],
  },
  {
    title: "Real-Time Gaming Backend",
    slug: "real-time-gaming-backend",
    description:
      "Design a real-time multiplayer gaming backend capable of supporting fast-paced online games (e.g., battle royale, FPS, MOBA). The system must handle game session matchmaking, authoritative game state management at low latency, real-time player synchronization, anti-cheat enforcement, and post-game statistics recording.",
    requirements: [
      "Matchmaking service: group players by skill (ELO/MMR), region, and game mode",
      "Allocate a dedicated game server for each match on demand",
      "Authoritative game server maintains and broadcasts game state",
      "Player clients send inputs; server validates and syncs state at ~60 Hz",
      "Anti-cheat: server-side validation of player actions; detect speed hacks, aimbots",
      "In-game chat and voice communication",
      "Post-match results: scores, kill/death, MVP, XP, and rank changes",
      "Persistent player profiles: stats, inventory, cosmetics, rank history",
      "Leaderboards and seasonal ranked ladders",
    ],
    constraints: [
      "Support 1M concurrent players in active matches",
      "Game state broadcast latency: < 50 ms within a region",
      "Matchmaking time: < 30 seconds for 95% of players",
      "Game server tick rate: 60 Hz (16.7 ms per tick)",
      "Match data (replay, events) stored for post-game analysis",
      "Scale up game server fleet by 2× within 5 minutes during peak",
      "99.99% availability for matchmaking and game server allocation",
    ],
    tags: ["WebSocket", "UDP", "game server", "matchmaking", "real-time", "anti-cheat", "auto-scaling", "latency-sensitive"],
    difficulty: "hard",
    referenceComponents: [
      "Matchmaking service with ELO/MMR-based queue and region-aware grouping",
      "Game server orchestrator (Kubernetes + Agones) for on-demand pod allocation",
      "Authoritative game loop server (UDP or WebSocket) with deterministic tick",
      "State replication via delta compression and snapshot interpolation",
      "Anti-cheat module: server-side physics validation and statistical anomaly detection",
      "Relay server / TURN server for NAT traversal and routing",
      "Post-game result processor: stats update, XP calculation, rank adjustment",
      "Player profile service (sharded database + Redis cache for hot profiles)",
      "Real-time leaderboard using Redis Sorted Sets",
    ],
  },
];

export default problems